//! A sealed `INTRODUCE` cell - the one a CLIENT can actually produce.
//!
//! # Why this exists
//!
//! [`crate::introduce::IntroduceCell`] authenticates with an Ed25519 signature
//! that the service verifies against the descriptor's `intro_auth_key`. That key
//! is a VERIFYING key whose private half is generated by the service and never
//! leaves it, so the only party who can produce an acceptable cell is the service
//! introducing to itself. No client can reach any service. The defect is pinned by
//! `crate::service::tests::no_client_can_produce_an_acceptable_introduce_cell`.
//!
//! # The fix, and why it is this one
//!
//! Tor's INTRODUCE1 is ENCRYPTED to the service, not signed by the client, and
//! that is the right shape here for the same reasons:
//!
//! - **Anyone holding the address can connect.** That is what "onion service"
//!   normally means. A signature scheme requires the service to have issued the
//!   client something first, which is a different product (client authorization)
//!   and can be layered on top of this rather than replacing it.
//! - **The introduction point still cannot read it.** It sees a public key it
//!   uses only for routing, and an opaque blob. It could not read the signed form
//!   either, so nothing is lost.
//! - **Nothing has to be distributed.** The sealing key comes out of the
//!   descriptor the client already fetched to learn the address exists.
//!
//! # Wire format
//!
//! ```text
//!  Offset  Size   Field
//!  ------  ----   -----
//!  0       32     client_eph_x25519_pk   (fresh per introduction)
//!  32      12     nonce
//!  44      N+16   ciphertext + tag, sealing the plaintext below
//! ```
//!
//! and the sealed plaintext is:
//!
//! ```text
//!  0       32     rendezvous_bridge_pk
//!  32      32     rendezvous_cookie
//!  64      8      issued_at (big-endian unix seconds)
//!  72      32     service_ed25519_pk
//! ```
//!
//! `service_ed25519_pk` is sealed IN so a coerced introduction point cannot
//! replay a captured cell at a different service: the plaintext names who it was
//! for, and the service checks it against itself.
//!
//! # Key agreement
//!
//! X25519 between the client's fresh ephemeral and the service's static
//! `service_x25519_pk` (published in the descriptor), run through BLAKE3 with a
//! domain label. The service derives the same secret from its own static secret
//! and the ephemeral carried in the clear at the front of the cell.
//!
//! This is deliberately NOT forward-secret for the introduction itself: an
//! adversary who later compromises the service's static key can decrypt recorded
//! INTRODUCE cells and learn which rendezvous points were used. Tor has the same
//! property for INTRODUCE1. What the cell carries is a meeting place and a
//! one-time cookie, both useless after the fact, and the end-to-end session that
//! follows gets its own ephemeral exchange.

use mirage_crypto::blake3;
use mirage_crypto::chacha20poly1305::{
    aead::{Aead, KeyInit, Payload},
    ChaCha20Poly1305, Key, Nonce,
};
use mirage_crypto::x25519_dalek::{PublicKey, StaticSecret};
use thiserror::Error;

/// Domain separation for the introduce sealing key.
const INTRO_KEY_LABEL: &[u8] = b"mirage-onion-introduce-v2";
/// AAD binding the ciphertext to this purpose.
const INTRO_AAD: &[u8] = b"mirage-onion-introduce-aad-v2";
/// ChaCha20-Poly1305 nonce length.
const NONCE_LEN: usize = 12;
/// Poly1305 tag length.
const TAG_LEN: usize = 16;
/// Sealed plaintext: rendezvous_bridge_pk + cookie + issued_at + service pk.
const PLAINTEXT_LEN: usize = 32 + 32 + 8 + 32;
/// Whole cell: client ephemeral + nonce + ciphertext + tag.
pub const SEALED_INTRODUCE_LEN: usize = 32 + NONCE_LEN + PLAINTEXT_LEN + TAG_LEN;

/// Errors from sealing or opening an introduction.
#[derive(Debug, Error, PartialEq, Eq)]
pub enum SealedIntroduceError {
    /// Wrong length for a sealed introduction.
    #[error("sealed introduce must be {SEALED_INTRODUCE_LEN} bytes, got {0}")]
    BadLength(usize),
    /// AEAD authentication failed: not for this service, or corrupt.
    #[error("introduce did not open (not sealed to this service, or corrupt)")]
    NotForUs,
    /// Opened, but names a different service than the one that opened it.
    #[error("introduce names a different service")]
    WrongService,
    /// Sealing failed (only possible on a broken RNG/key).
    #[error("introduce seal failed")]
    SealFailed,
}

/// What a client asks for, and what the service reads back out.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Introduction {
    /// Ed25519 identity of the bridge where the two will meet.
    pub rendezvous_bridge_pk: [u8; 32],
    /// One-time meeting token the client parked at that bridge.
    pub rendezvous_cookie: [u8; 32],
    /// Unix seconds the cell was minted; bounds the replay window.
    pub issued_at: u64,
    /// The service this was meant for, sealed in so a captured cell cannot be
    /// replayed at a different one.
    pub service_ed25519_pk: [u8; 32],
}

impl Introduction {
    fn encode(&self) -> [u8; PLAINTEXT_LEN] {
        let mut out = [0u8; PLAINTEXT_LEN];
        out[..32].copy_from_slice(&self.rendezvous_bridge_pk);
        out[32..64].copy_from_slice(&self.rendezvous_cookie);
        out[64..72].copy_from_slice(&self.issued_at.to_be_bytes());
        out[72..].copy_from_slice(&self.service_ed25519_pk);
        out
    }

    fn decode(b: &[u8]) -> Option<Self> {
        if b.len() != PLAINTEXT_LEN {
            return None;
        }
        let mut rendezvous_bridge_pk = [0u8; 32];
        let mut rendezvous_cookie = [0u8; 32];
        let mut service_ed25519_pk = [0u8; 32];
        let mut ts = [0u8; 8];
        rendezvous_bridge_pk.copy_from_slice(&b[..32]);
        rendezvous_cookie.copy_from_slice(&b[32..64]);
        ts.copy_from_slice(&b[64..72]);
        service_ed25519_pk.copy_from_slice(&b[72..]);
        Some(Self {
            rendezvous_bridge_pk,
            rendezvous_cookie,
            issued_at: u64::from_be_bytes(ts),
            service_ed25519_pk,
        })
    }

    /// Whether this is inside the validity window either side of `now_unix`.
    ///
    /// Both directions: a clock-skewed future cell is as suspect as a stale one,
    /// and accepting the future would let one captured cell be held and used.
    #[must_use]
    pub fn is_fresh(&self, now_unix: u64) -> bool {
        let w = crate::introduce::INTRODUCE_VALIDITY_SECS;
        now_unix.abs_diff(self.issued_at) <= w
    }
}

/// Derive the sealing key from an X25519 shared secret.
fn key_from(shared: &[u8; 32], client_eph: &[u8; 32], service_x: &[u8; 32]) -> [u8; 32] {
    // Both public keys are bound in, so the key is specific to this pair and a
    // shared secret cannot be reused across a different framing.
    let mut h = blake3::Hasher::new();
    h.update(INTRO_KEY_LABEL);
    h.update(shared);
    h.update(client_eph);
    h.update(service_x);
    *h.finalize().as_bytes()
}

/// Seal an introduction to a service. What a CLIENT calls.
///
/// `client_eph_sk` must be freshly generated per introduction: it is the only
/// thing keeping two introductions from the same client unlinkable to the
/// introduction point.
///
/// # Errors
/// [`SealedIntroduceError::SealFailed`] only on a broken AEAD.
pub fn seal_introduce(
    intro: &Introduction,
    service_x25519_pk: &[u8; 32],
    client_eph_sk: &[u8; 32],
    nonce_bytes: &[u8; NONCE_LEN],
) -> Result<Vec<u8>, SealedIntroduceError> {
    let eph = StaticSecret::from(*client_eph_sk);
    let eph_pk = *PublicKey::from(&eph).as_bytes();
    let shared = *eph
        .diffie_hellman(&PublicKey::from(*service_x25519_pk))
        .as_bytes();
    let key = key_from(&shared, &eph_pk, service_x25519_pk);

    let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
    let ct = cipher
        .encrypt(
            Nonce::from_slice(nonce_bytes),
            Payload {
                msg: &intro.encode(),
                aad: INTRO_AAD,
            },
        )
        .map_err(|_| SealedIntroduceError::SealFailed)?;

    let mut out = Vec::with_capacity(SEALED_INTRODUCE_LEN);
    out.extend_from_slice(&eph_pk);
    out.extend_from_slice(nonce_bytes);
    out.extend_from_slice(&ct);
    Ok(out)
}

/// Open an introduction sealed to us. What a SERVICE calls.
///
/// Checks that the sealed plaintext names THIS service, so a coerced
/// introduction point cannot replay a captured cell elsewhere.
///
/// # Errors
/// [`SealedIntroduceError::BadLength`], [`SealedIntroduceError::NotForUs`] when
/// the AEAD does not authenticate, or [`SealedIntroduceError::WrongService`].
pub fn open_introduce(
    sealed: &[u8],
    service_x25519_sk: &[u8; 32],
    service_ed25519_pk: &[u8; 32],
) -> Result<Introduction, SealedIntroduceError> {
    if sealed.len() != SEALED_INTRODUCE_LEN {
        return Err(SealedIntroduceError::BadLength(sealed.len()));
    }
    let mut eph_pk = [0u8; 32];
    eph_pk.copy_from_slice(&sealed[..32]);
    let mut nonce = [0u8; NONCE_LEN];
    nonce.copy_from_slice(&sealed[32..32 + NONCE_LEN]);

    let sk = StaticSecret::from(*service_x25519_sk);
    let service_x_pk = *PublicKey::from(&sk).as_bytes();
    let shared = *sk.diffie_hellman(&PublicKey::from(eph_pk)).as_bytes();
    let key = key_from(&shared, &eph_pk, &service_x_pk);

    let cipher = ChaCha20Poly1305::new(Key::from_slice(&key));
    let pt = cipher
        .decrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: &sealed[32 + NONCE_LEN..],
                aad: INTRO_AAD,
            },
        )
        .map_err(|_| SealedIntroduceError::NotForUs)?;

    let intro = Introduction::decode(&pt).ok_or(SealedIntroduceError::NotForUs)?;
    if &intro.service_ed25519_pk != service_ed25519_pk {
        return Err(SealedIntroduceError::WrongService);
    }
    Ok(intro)
}

/// A replay key for the service's cache: the ciphertext is unique per cell.
#[must_use]
pub fn replay_key(sealed: &[u8]) -> [u8; 32] {
    *blake3::hash(sealed).as_bytes()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn keys() -> ([u8; 32], [u8; 32], [u8; 32]) {
        let sk = StaticSecret::from([7u8; 32]);
        let pk = *PublicKey::from(&sk).as_bytes();
        (sk.to_bytes(), pk, [9u8; 32])
    }

    fn intro(svc_ed: [u8; 32], at: u64) -> Introduction {
        Introduction {
            rendezvous_bridge_pk: [1u8; 32],
            rendezvous_cookie: [2u8; 32],
            issued_at: at,
            service_ed25519_pk: svc_ed,
        }
    }

    #[test]
    fn a_client_holding_only_the_descriptor_can_introduce() {
        // THE point of this module. A client knows the service's PUBLIC keys and
        // nothing else - which is all a descriptor carries - and that has to be
        // enough. Under the signed scheme it was not: the only acceptable signer
        // was the service itself.
        let (svc_x_sk, svc_x_pk, svc_ed) = keys();
        let want = intro(svc_ed, 1_000);
        let sealed = seal_introduce(&want, &svc_x_pk, &[42u8; 32], &[3u8; NONCE_LEN])
            .expect("a client can seal with public info alone");
        let got = open_introduce(&sealed, &svc_x_sk, &svc_ed).expect("service opens it");
        assert_eq!(got, want);
        assert_eq!(sealed.len(), SEALED_INTRODUCE_LEN);
    }

    #[test]
    fn the_introduction_point_cannot_read_it() {
        // An introduction point forwards the blob and is not entitled to its
        // contents. It holds no service secret, so it must not be able to open it
        // with anything it does have.
        let (_svc_x_sk, svc_x_pk, svc_ed) = keys();
        let sealed = seal_introduce(
            &intro(svc_ed, 1_000),
            &svc_x_pk,
            &[42u8; 32],
            &[3u8; NONCE_LEN],
        )
        .unwrap();
        // Any other X25519 secret - which is all an intro point could bring.
        let other = StaticSecret::from([11u8; 32]).to_bytes();
        assert_eq!(
            open_introduce(&sealed, &other, &svc_ed),
            Err(SealedIntroduceError::NotForUs)
        );
    }

    #[test]
    fn a_captured_cell_cannot_be_replayed_at_another_service() {
        // A coerced introduction point holds a real cell. The service it was
        // sealed to is named INSIDE the seal, so pointing it at a different
        // service fails even if that service could somehow decrypt it.
        let (svc_x_sk, svc_x_pk, svc_ed) = keys();
        let sealed = seal_introduce(
            &intro(svc_ed, 1_000),
            &svc_x_pk,
            &[42u8; 32],
            &[3u8; NONCE_LEN],
        )
        .unwrap();
        let someone_else = [0xAAu8; 32];
        assert_eq!(
            open_introduce(&sealed, &svc_x_sk, &someone_else),
            Err(SealedIntroduceError::WrongService)
        );
    }

    #[test]
    fn tampering_anywhere_is_caught() {
        let (svc_x_sk, svc_x_pk, svc_ed) = keys();
        let sealed = seal_introduce(
            &intro(svc_ed, 1_000),
            &svc_x_pk,
            &[42u8; 32],
            &[3u8; NONCE_LEN],
        )
        .unwrap();
        for i in [0usize, 31, 32, 40, SEALED_INTRODUCE_LEN - 1] {
            let mut bad = sealed.clone();
            bad[i] ^= 1;
            assert!(
                open_introduce(&bad, &svc_x_sk, &svc_ed).is_err(),
                "flipping byte {i} must not open"
            );
        }
        assert_eq!(
            open_introduce(&sealed[..10], &svc_x_sk, &svc_ed),
            Err(SealedIntroduceError::BadLength(10))
        );
    }

    #[test]
    fn freshness_is_bounded_in_both_directions() {
        let i = intro([9u8; 32], 1_000);
        assert!(i.is_fresh(1_000));
        assert!(i.is_fresh(1_000 + crate::introduce::INTRODUCE_VALIDITY_SECS));
        assert!(!i.is_fresh(1_001 + crate::introduce::INTRODUCE_VALIDITY_SECS));
        // A future-dated cell is as suspect as a stale one: accepting it would
        // let a captured cell be held and used later.
        assert!(!i.is_fresh(1_000 - crate::introduce::INTRODUCE_VALIDITY_SECS - 1));
    }

    #[test]
    fn each_introduction_looks_unrelated_to_the_introduction_point() {
        // Two introductions to the SAME service must not be linkable by anything
        // the introduction point sees. The ephemeral is the only thing keeping
        // that true, so it has to actually change the whole blob.
        let (_sk, svc_x_pk, svc_ed) = keys();
        let a = seal_introduce(
            &intro(svc_ed, 1_000),
            &svc_x_pk,
            &[1u8; 32],
            &[3u8; NONCE_LEN],
        )
        .unwrap();
        let b = seal_introduce(
            &intro(svc_ed, 1_000),
            &svc_x_pk,
            &[2u8; 32],
            &[3u8; NONCE_LEN],
        )
        .unwrap();
        assert_ne!(a, b, "different ephemerals must give unlinkable cells");
        assert_ne!(&a[..32], &b[..32]);
        assert_ne!(replay_key(&a), replay_key(&b));
    }
}
