//! TLS 1.3 ClientHello generator.
//!
//! Emits the exact wire bytes a Mirage client places on the TCP
//! stream when the Reality carrier is active. The produced bytes
//! decode cleanly via [`parse_client_hello_record`]
//! (the bridge-side parser we already fuzz-tested) so there's no
//! risk of generator/parser drift.
//!
//! # Fingerprint
//!
//! The shape mimics a recent Chrome-on-desktop ClientHello: TLS 1.3 via
//! `supported_versions`, the hybrid X25519MLKEM768 `key_share` (with a real
//! ML-KEM ek) alongside X25519, the full modern-Chrome extension SET
//! (server_name, EMS, renegotiation_info, supported_groups, ec_point_formats,
//! session_ticket, ALPN, status_request, signature_algorithms, SCT, key_share,
//! psk_key_exchange_modes, supported_versions, compress_certificate, ALPS),
//! GREASE in the first + last extension slots and in the cipher / group /
//! key_share / supported_versions lists (RFC 8701), and a per-connection
//! **shuffled** extension order (F4 - real Chrome/BoringSSL permutes every
//! connection, so its JA3 varies and its JA4 stays stable).
//!
//! Known residual (tracked): the `signature_algorithms` list still advertises
//! `ed25519`, which desktop Chrome does not offer, because the Reality
//! CertVerify signs with ed25519. Removing it requires switching the cert +
//! CertVerify to ECDSA-P256 (a new EC dependency + a variable-length-DER
//! signature path); until then a JA4 (which hashes sig_algs) can still tell
//! this apart from Chrome, though JA3 (which excludes sig_algs) matches.
//!
//! # What this does NOT do
//!
//! - **Real TLS 1.3 crypto.** We do not derive handshake keys. The
//!   `key_share` public we emit is the X25519 ephemeral the probe
//!   layer uses; the corresponding private stays with the client
//!   and is consumed by the bridge's probe verification.
//! - **Certificate verification.** No handshake completes at this
//!   layer; the consumer treats successful probe verification as
//!   authentication and moves on.
//!
//! # Threat-model notes
//!
//! - Against **passive protocol DPI** (firewalls that classify by
//!   first-record pattern): the generated bytes parse as a valid
//!   TLS 1.3 ClientHello with common extensions. Passes.
//! - Against **active probers that expect a real TLS ServerHello +
//!   real Finished** (GFW-style): this generator on its own is
//!   NOT sufficient. The `carrier` module's bridge side responds
//!   with a synthesized ServerHello but does NOT run real TLS key
//!   derivation. An active prober that tries to complete the
//!   handshake will see divergent behavior. Deferred to v0.1b.
//! - Against **correlation attacks** (same `random` across
//!   connections): we always draw `random` from the OS CSPRNG.
//!   `session_id` is the per-probe output of the auth probe
//!   construction, so uniqueness is already enforced at that layer.

use crate::error::RealityError;
use crate::tls_client_hello::MAX_CLIENT_HELLO_SIZE;
use crate::tls_fingerprint::{
    GreaseValues, TlsFingerprintTemplate, CHROME_DESKTOP, EXT_ALPN, EXT_APPLICATION_SETTINGS,
    EXT_COMPRESS_CERTIFICATE, EXT_EC_POINT_FORMATS, EXT_ENCRYPTED_CLIENT_HELLO,
    EXT_EXTENDED_MASTER_SECRET, EXT_KEY_SHARE, EXT_PSK_KEY_EXCHANGE_MODES, EXT_RECORD_SIZE_LIMIT,
    EXT_RENEGOTIATION_INFO, EXT_SERVER_NAME, EXT_SESSION_TICKET, EXT_SIGNATURE_ALGORITHMS,
    EXT_SIGNED_CERT_TIMESTAMP, EXT_STATUS_REQUEST, EXT_SUPPORTED_GROUPS, EXT_SUPPORTED_VERSIONS,
    GROUP_X25519, GROUP_X25519_MLKEM768,
};

/// ML-KEM-768 encapsulation-key wire length (the hybrid key_share's ek half).
const MLKEM_EK_LEN: usize = 1184;

// TLS wire constants (RFC 8446). Private to this module; callers
// consume whole records via [`build_client_hello`].

const RECORD_TYPE_HANDSHAKE: u8 = 0x16;
const LEGACY_RECORD_VERSION: [u8; 2] = [0x03, 0x01]; // TLS 1.0 per RFC 8446
const HANDSHAKE_TYPE_CLIENT_HELLO: u8 = 0x01;

/// Inputs for [`build_client_hello`].
///
/// `random` MUST come from a CSPRNG; never reuse across connections.
/// `session_id` is the 32-byte Reality auth probe output
/// ([`crate::probe::Probe::encode`]).
/// `x25519_key_share` is the client's ephemeral X25519 public; the
/// corresponding private stayed in [`crate::probe::build_probe`].
/// `server_name` is the SNI written into the ClientHello (set this
/// to the cover-destination hostname so traffic inspection sees a
/// sensible name).
pub struct ClientHelloInputs<'a> {
    /// 32-byte fresh random.
    pub random: &'a [u8; 32],
    /// 32-byte probe bytes placed verbatim in `legacy_session_id`.
    pub session_id: &'a [u8; 32],
    /// Client's X25519 ephemeral public key.
    pub x25519_key_share: &'a [u8; 32],
    /// SNI to include (cover-destination hostname).
    pub server_name: &'a str,
    /// If true, the ALPN extension is included with the protocols
    /// from the template. Set false to override the template and
    /// omit ALPN. Default-recommended: true.
    pub include_alpn: bool,
    /// Browser-mimicry template driving cipher suites, extension
    /// order, signature-algorithm list, and ALPN protocols. See
    /// [`crate::tls_fingerprint`]. Default: `&CHROME_DESKTOP`.
    pub fingerprint: &'a TlsFingerprintTemplate,
    /// Optional per-connection GREASE (RFC 8701). `Some` injects GREASE into
    /// the cipher list, `supported_groups`, `key_share`, and the leading
    /// extension slot - matching real Chrome/Firefox. GREASE is excluded from
    /// JA3 by spec, so it does not change the pinned JA3 string. `None` emits
    /// no GREASE (deterministic; used by tests). Production SHOULD pass `Some`.
    pub grease: Option<GreaseValues>,
    /// Optional real ML-KEM-768 encapsulation key (1184 B). When `Some` AND the
    /// template advertises [`GROUP_X25519_MLKEM768`], a hybrid X25519MLKEM768
    /// `key_share` entry is emitted FIRST (`ek || x25519`), matching Chrome 124+
    /// / Firefox 132+. MUST be a real ek (a censor can range-check the ML-KEM
    /// polynomial coefficients), never random bytes. Cover-only at the TLS
    /// layer - Mirage's real PQ KEM lives inside the Noise session.
    pub mlkem_ek: Option<&'a [u8; MLKEM_EK_LEN]>,
}

impl<'a> ClientHelloInputs<'a> {
    /// Convenience constructor using the default Chrome fingerprint
    /// template. Equivalent to setting `fingerprint:
    /// &CHROME_DESKTOP` by hand.
    pub fn with_defaults(
        random: &'a [u8; 32],
        session_id: &'a [u8; 32],
        x25519_key_share: &'a [u8; 32],
        server_name: &'a str,
    ) -> Self {
        Self {
            random,
            session_id,
            x25519_key_share,
            server_name,
            include_alpn: true,
            fingerprint: &CHROME_DESKTOP,
            grease: None,
            mlkem_ek: None,
        }
    }
}

/// Produce the wire bytes of a TLS 1.3 ClientHello record driven
/// by a fingerprint template. The template defines cipher suites,
/// extension order, signature algorithms, ALPN protocols, and
/// optional legacy extensions; this function fills in the dynamic
/// bits (random, session_id, key_share pubkey, SNI) and emits
/// ready-to-write bytes.
pub fn build_client_hello(inputs: &ClientHelloInputs<'_>) -> Result<Vec<u8>, RealityError> {
    if inputs.server_name.is_empty() || inputs.server_name.len() > 253 {
        return Err(RealityError::TagMismatch); // caller maps to protocol error
    }
    for b in inputs.server_name.bytes() {
        // ASCII hostname characters only; anti-smuggling.
        if !(b.is_ascii_alphanumeric() || matches!(b, b'.' | b'-')) {
            return Err(RealityError::TagMismatch);
        }
    }
    let tpl = inputs.fingerprint;
    // Invariants: template MUST include key_share + supported_versions +
    // server_name (Mirage bridge needs them) AND advertise x25519.
    if !tpl.extension_order.contains(&EXT_KEY_SHARE)
        || !tpl.extension_order.contains(&EXT_SUPPORTED_VERSIONS)
        || !tpl.extension_order.contains(&EXT_SERVER_NAME)
        || !tpl.supported_groups.contains(&GROUP_X25519)
    {
        return Err(RealityError::TagMismatch);
    }
    if tpl.cipher_suites.is_empty() {
        return Err(RealityError::TagMismatch);
    }

    // Build extensions body first so we can length-prefix it. Order
    // is driven by `extension_order` verbatim.
    let mut ext = Vec::with_capacity(384);
    // RFC 8701: real Chrome places a GREASE extension in the FIRST slot.
    // Injected at emit time - NOT added to template.extension_order, which
    // feeds the JA3 string (GREASE must stay out of JA3).
    if let Some(g) = inputs.grease {
        write_extension(&mut ext, g.ext_first, &[]);
    }
    // F4: real Chrome (BoringSSL) permutes its extension order per connection -
    // a *static* order is itself a distinguisher (a client whose extension
    // sequence never changes is not Chrome; modern Chrome's JA3 varies per
    // connection, and its JA4 - which sorts extensions - stays stable). Shuffle
    // in production (grease=Some); keep the canonical template order for
    // deterministic tests (grease=None). The GREASE first/last slots wrap the
    // permutation, matching BoringSSL.
    let mut order: Vec<u16> = tpl.extension_order.to_vec();
    if inputs.grease.is_some() {
        shuffle_extensions(&mut order);
    }
    for &ext_type in &order {
        match ext_type {
            EXT_SERVER_NAME => write_ext_server_name(&mut ext, inputs.server_name),
            EXT_SUPPORTED_GROUPS => {
                if let Some(g) = inputs.grease {
                    // RFC 8701: prepend the GREASE group. The SAME value is
                    // reused for the key_share GREASE entry (Chrome correlates
                    // the two), so a fingerprinter can't split them.
                    let mut groups = Vec::with_capacity(tpl.supported_groups.len() + 1);
                    groups.push(g.group);
                    groups.extend_from_slice(tpl.supported_groups);
                    write_u16_list_ext(&mut ext, ext_type, &groups);
                } else {
                    write_u16_list_ext(&mut ext, ext_type, tpl.supported_groups);
                }
            }
            EXT_SIGNATURE_ALGORITHMS => {
                write_u16_list_ext(&mut ext, ext_type, tpl.sig_algs);
            }
            EXT_ALPN => {
                if inputs.include_alpn && !tpl.alpn_protos.is_empty() {
                    write_ext_alpn(&mut ext, tpl.alpn_protos);
                }
            }
            EXT_SUPPORTED_VERSIONS => {
                write_ext_supported_versions(&mut ext, inputs.grease.map(|g| g.version))
            }
            EXT_KEY_SHARE => {
                // Emit the hybrid X25519MLKEM768 entry ONLY when the template
                // actually advertises 0x11EC in supported_groups - keeps
                // advertised-groups consistent with sent-key_shares (a
                // mismatch is itself a distinguisher).
                let hybrid_ek = inputs
                    .mlkem_ek
                    .filter(|_| tpl.supported_groups.contains(&GROUP_X25519_MLKEM768));
                write_ext_key_share(
                    &mut ext,
                    inputs.x25519_key_share,
                    inputs.grease.map(|g| g.group),
                    hybrid_ek,
                );
            }
            EXT_EC_POINT_FORMATS => {
                if !tpl.ec_point_formats.is_empty() {
                    write_u8_list_ext(&mut ext, ext_type, tpl.ec_point_formats);
                }
            }
            EXT_PSK_KEY_EXCHANGE_MODES => {
                if !tpl.psk_key_exchange_modes.is_empty() {
                    write_u8_list_ext(&mut ext, ext_type, tpl.psk_key_exchange_modes);
                }
            }
            EXT_EXTENDED_MASTER_SECRET => {
                if tpl.extended_master_secret {
                    write_extension(&mut ext, ext_type, &[]);
                }
            }
            EXT_RENEGOTIATION_INFO => {
                if tpl.renegotiation_info {
                    // RFC 5746: `renegotiated_connection` is a
                    // 1-byte length of 0 followed by 0 bytes. On
                    // an initial ClientHello the field is an empty
                    // length-prefixed vector.
                    write_extension(&mut ext, ext_type, &[0x00]);
                }
            }
            EXT_RECORD_SIZE_LIMIT => {
                if let Some(limit) = tpl.record_size_limit {
                    write_extension(&mut ext, ext_type, &limit.to_be_bytes());
                }
            }
            EXT_STATUS_REQUEST => {
                // status_type=ocsp(1) + responder_id_list len(2)=0 + request
                // extensions len(2)=0 - Chrome's empty OCSP-stapling request.
                write_extension(&mut ext, ext_type, &[0x01, 0x00, 0x00, 0x00, 0x00]);
            }
            EXT_SIGNED_CERT_TIMESTAMP | EXT_SESSION_TICKET => {
                // Both are advertised with an empty body in a fresh Chrome
                // ClientHello (no cached ticket, empty SCT request).
                write_extension(&mut ext, ext_type, &[]);
            }
            EXT_COMPRESS_CERTIFICATE => {
                // algorithms list: 1-byte length(2) + brotli(0x0002).
                write_extension(&mut ext, ext_type, &[0x02, 0x00, 0x02]);
            }
            EXT_APPLICATION_SETTINGS => {
                // ALPS: supported ALPN list, Chrome advertises just `h2`.
                write_ext_alps(&mut ext, &[b"h2"]);
            }
            EXT_ENCRYPTED_CLIENT_HELLO => {
                // GREASE ECH - production only (random payload). Deterministic
                // test path (grease=None) omits it to stay reproducible.
                if inputs.grease.is_some() {
                    write_ext_ech_grease(&mut ext);
                }
            }
            // Unknown (or unrecognised) extension type in template:
            // emit an empty body. A template should only reference
            // types this generator knows how to render; a mismatch
            // is a template bug, not a client-input bug.
            _ => write_extension(&mut ext, ext_type, &[]),
        }
    }

    // RFC 8701: real Chrome also places a SECOND, distinct GREASE extension in
    // the LAST slot (empty body). Emitted at build time - kept out of
    // template.extension_order so the JA3 string is unaffected.
    if let Some(g) = inputs.grease {
        write_extension(&mut ext, g.ext_last, &[]);
    }

    // Build ClientHello body.
    let mut body = Vec::with_capacity(300);
    body.extend_from_slice(&tpl.legacy_version); // legacy_version
    body.extend_from_slice(inputs.random); // 32B random
    body.push(32u8); // session_id length
    body.extend_from_slice(inputs.session_id); // session_id
                                               // cipher_suites
                                               // RFC 8701: a single GREASE cipher is PREPENDED to the suite list.
    let grease_cipher = inputs.grease.map(|g| g.cipher);
    let cs_count = tpl.cipher_suites.len() + usize::from(grease_cipher.is_some());
    let cs_len = (cs_count * 2) as u16;
    body.extend_from_slice(&cs_len.to_be_bytes());
    if let Some(gc) = grease_cipher {
        body.extend_from_slice(&gc.to_be_bytes());
    }
    for &cs in tpl.cipher_suites {
        body.extend_from_slice(&cs.to_be_bytes());
    }
    // legacy_compression_methods
    body.push(tpl.compression_methods.len() as u8);
    body.extend_from_slice(tpl.compression_methods);
    // extensions
    let ext_len: u16 = u16::try_from(ext.len()).map_err(|_| RealityError::TagMismatch)?;
    body.extend_from_slice(&ext_len.to_be_bytes());
    body.extend_from_slice(&ext);

    // Wrap in handshake header: type(1) + len(3) + body
    let body_len: u32 = u32::try_from(body.len()).map_err(|_| RealityError::TagMismatch)?;
    let mut hs = Vec::with_capacity(4 + body.len());
    hs.push(HANDSHAKE_TYPE_CLIENT_HELLO);
    // 24-bit big-endian length
    hs.push(((body_len >> 16) & 0xFF) as u8);
    hs.push(((body_len >> 8) & 0xFF) as u8);
    hs.push((body_len & 0xFF) as u8);
    hs.extend_from_slice(&body);

    // Wrap in record header: type(1) + version(2) + len(2) + payload
    let rec_len: u16 = u16::try_from(hs.len()).map_err(|_| RealityError::TagMismatch)?;
    let mut rec = Vec::with_capacity(5 + hs.len());
    rec.push(RECORD_TYPE_HANDSHAKE);
    rec.extend_from_slice(&LEGACY_RECORD_VERSION);
    rec.extend_from_slice(&rec_len.to_be_bytes());
    rec.extend_from_slice(&hs);

    if rec.len() > MAX_CLIENT_HELLO_SIZE {
        return Err(RealityError::TagMismatch);
    }
    Ok(rec)
}

// Extension writers

fn write_extension(out: &mut Vec<u8>, ext_type: u16, body: &[u8]) {
    out.extend_from_slice(&ext_type.to_be_bytes());
    out.extend_from_slice(&(body.len() as u16).to_be_bytes());
    out.extend_from_slice(body);
}

/// Fisher-Yates permutation of the extension order via the OS CSPRNG (F4). On
/// CSPRNG failure the canonical order is left intact (still a valid, if static,
/// ClientHello). Consumes 4 random bytes per swap; the modulo bias for a list
/// of <=16 extensions against a 32-bit draw is ~10^-9 - irrelevant for cover
/// ordering.
fn shuffle_extensions(order: &mut [u16]) {
    let n = order.len();
    if n < 2 {
        return;
    }
    let mut rnd = [0u8; 64];
    if getrandom::fill(&mut rnd).is_err() {
        return;
    }
    for (step, i) in (1..n).rev().enumerate() {
        let mut word = [0u8; 4];
        for (w, slot) in word.iter_mut().enumerate() {
            *slot = rnd.get((step * 4 + w) % rnd.len()).copied().unwrap_or(0);
        }
        let r = u32::from_le_bytes(word) as usize;
        order.swap(i, r % (i + 1));
    }
}

fn write_ext_server_name(out: &mut Vec<u8>, name: &str) {
    // SNI: list_len(2) + name_type(1)=host_name + host_name_len(2) + host_name
    let name_bytes = name.as_bytes();
    let entry_len = 1 + 2 + name_bytes.len();
    let mut body = Vec::with_capacity(2 + entry_len);
    body.extend_from_slice(&(entry_len as u16).to_be_bytes());
    body.push(0x00); // host_name type
    body.extend_from_slice(&(name_bytes.len() as u16).to_be_bytes());
    body.extend_from_slice(name_bytes);
    write_extension(out, EXT_SERVER_NAME, &body);
}

/// Generic writer for "list of u16 with 2-byte length prefix"
/// extensions (supported_groups, signature_algorithms).
fn write_u16_list_ext(out: &mut Vec<u8>, ext_type: u16, values: &[u16]) {
    let mut body = Vec::with_capacity(2 + 2 * values.len());
    body.extend_from_slice(&((values.len() * 2) as u16).to_be_bytes());
    for v in values {
        body.extend_from_slice(&v.to_be_bytes());
    }
    write_extension(out, ext_type, &body);
}

/// Generic writer for "list of u8 with 1-byte length prefix"
/// extensions (ec_point_formats, psk_key_exchange_modes).
fn write_u8_list_ext(out: &mut Vec<u8>, ext_type: u16, values: &[u8]) {
    let mut body = Vec::with_capacity(1 + values.len());
    body.push(values.len() as u8);
    body.extend_from_slice(values);
    write_extension(out, ext_type, &body);
}

fn write_ext_alpn(out: &mut Vec<u8>, protos: &[&[u8]]) {
    // ALPN: protocols list, each entry = len(1) + name.
    let mut list = Vec::new();
    for p in protos {
        list.push(p.len() as u8);
        list.extend_from_slice(p);
    }
    let mut body = Vec::with_capacity(2 + list.len());
    body.extend_from_slice(&(list.len() as u16).to_be_bytes());
    body.extend_from_slice(&list);
    write_extension(out, EXT_ALPN, &body);
}

/// ALPS (`application_settings`): identical wire shape to ALPN - a 2-byte
/// length-prefixed list of `len(1) + name` entries. Chrome advertises `h2`.
fn write_ext_alps(out: &mut Vec<u8>, protos: &[&[u8]]) {
    let mut list = Vec::new();
    for p in protos {
        list.push(p.len() as u8);
        list.extend_from_slice(p);
    }
    let mut body = Vec::with_capacity(2 + list.len());
    body.extend_from_slice(&(list.len() as u16).to_be_bytes());
    body.extend_from_slice(&list);
    write_extension(out, EXT_APPLICATION_SETTINGS, &body);
}

fn write_ext_supported_versions(out: &mut Vec<u8>, grease_version: Option<u16>) {
    // ClientHello form: list_len(1) + versions(2 each). Real Chrome sends
    // `[GREASE, 0x0304, 0x0303]` - a GREASE version, then TLS 1.3, then TLS 1.2.
    // The GREASE value lives in the extension BODY, not the extension list, so it
    // does not change the JA3 string.
    //
    // TLS 1.2 (0x0303) MUST be offered even though the Reality bridge only ever
    // selects 1.3: EVERY real browser advertises the 1.2 fallback, so a
    // 1.3-only supported_versions is a browser-impossible tell a body-parsing
    // DPI (the GFW) pins directly (red-team HIGH #2). Advertising 1.2 here is
    // cover-only - the server still emits a single selected_version = 1.3.
    let n = 2 + usize::from(grease_version.is_some());
    let mut body = Vec::with_capacity(1 + 2 * n);
    body.push((2 * n) as u8);
    if let Some(gv) = grease_version {
        body.extend_from_slice(&gv.to_be_bytes());
    }
    body.extend_from_slice(&[0x03, 0x04]); // TLS 1.3
    body.extend_from_slice(&[0x03, 0x03]); // TLS 1.2 (fallback; never selected)
    write_extension(out, EXT_SUPPORTED_VERSIONS, &body);
}

/// Payload length of the GREASE `encrypted_client_hello` extension's inner
/// `payload` field. Chrome pads its GREASE ECH so the extension is a stable
/// size; 176 bytes (a plausible encrypted-ClientHelloInner + AEAD tag) keeps the
/// whole ECH extension in Chrome's observed ~200-240 B band.
const ECH_GREASE_PAYLOAD_LEN: usize = 176;

/// Write a GREASE `encrypted_client_hello` (outer) extension (RFC 9180 /
/// draft-ietf-tls-esni ECHClientHello, type=outer). The content is random per
/// connection (Chrome/Firefox do the same for GREASE ECH), but the framing is
/// structurally valid and range-checkable: outer type, a real HPKE cipher suite
/// (HKDF-SHA256 + AES-128-GCM), a 1-byte config_id, a 32-byte X25519 `enc`, and
/// a fixed-length random `payload`. Emitted only in production (grease=Some);
/// the deterministic test path omits it to stay reproducible.
fn write_ext_ech_grease(out: &mut Vec<u8>) {
    let mut rnd = [0u8; 1 + 32 + ECH_GREASE_PAYLOAD_LEN];
    if getrandom::fill(&mut rnd).is_err() {
        // On CSPRNG failure, emit nothing rather than a fixed (fingerprintable)
        // payload; the shuffled order simply lacks ECH this once.
        return;
    }
    let mut body = Vec::with_capacity(1 + 4 + 1 + 2 + 32 + 2 + ECH_GREASE_PAYLOAD_LEN);
    body.push(0x00); // ECHClientHelloType = outer(0)
    body.extend_from_slice(&0x0001u16.to_be_bytes()); // HpkeKdfId = HKDF-SHA256
    body.extend_from_slice(&0x0001u16.to_be_bytes()); // HpkeAeadId = AES-128-GCM
    body.push(rnd[0]); // config_id (1 random byte)
    body.extend_from_slice(&32u16.to_be_bytes()); // enc<0..2^16-1> length = 32
    body.extend_from_slice(&rnd[1..33]); // enc: a fresh random X25519 public
    body.extend_from_slice(&(ECH_GREASE_PAYLOAD_LEN as u16).to_be_bytes());
    body.extend_from_slice(&rnd[33..]); // payload: random, fixed-length bucket
    write_extension(out, EXT_ENCRYPTED_CLIENT_HELLO, &body);
}

fn write_ext_key_share(
    out: &mut Vec<u8>,
    x25519_pub: &[u8; 32],
    grease_group: Option<u16>,
    hybrid_ek: Option<&[u8; MLKEM_EK_LEN]>,
) {
    // Entries in real-Chrome order: [GREASE] [hybrid X25519MLKEM768] [X25519].
    // Each entry: named_group(2) + key_exchange_len(2) + key_exchange.
    let mut entries = Vec::with_capacity(2 + 2 + 32);
    // GREASE key_share entry: group=GREASE, 1-byte 0x00 key_exchange (Chrome
    // uses a single zero byte, NOT 0-length and NOT a full-size share).
    if let Some(gg) = grease_group {
        entries.extend_from_slice(&gg.to_be_bytes());
        entries.extend_from_slice(&1u16.to_be_bytes());
        entries.push(0x00);
    }
    // Hybrid entry: group 0x11EC, key_exchange = ml-kem-768 ek(1184) || x25519(32).
    if let Some(ek) = hybrid_ek {
        let kx_len = (MLKEM_EK_LEN + 32) as u16; // 1216
        entries.extend_from_slice(&GROUP_X25519_MLKEM768.to_be_bytes());
        entries.extend_from_slice(&kx_len.to_be_bytes());
        entries.extend_from_slice(ek);
        entries.extend_from_slice(x25519_pub);
    }
    // X25519 fallback entry - the share Mirage's Reality handshake actually uses.
    entries.extend_from_slice(&GROUP_X25519.to_be_bytes());
    entries.extend_from_slice(&(32u16).to_be_bytes());
    entries.extend_from_slice(x25519_pub);

    // client_shares_len(2) prefixes the concatenated entries.
    let mut body = Vec::with_capacity(2 + entries.len());
    body.extend_from_slice(&(entries.len() as u16).to_be_bytes());
    body.extend_from_slice(&entries);
    write_extension(out, EXT_KEY_SHARE, &body);
}

// Tests

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tls_client_hello::parse_client_hello_record;

    fn sample_inputs<'a>(
        rnd: &'a [u8; 32],
        sid: &'a [u8; 32],
        ks: &'a [u8; 32],
    ) -> ClientHelloInputs<'a> {
        ClientHelloInputs {
            random: rnd,
            session_id: sid,
            x25519_key_share: ks,
            server_name: "example.com",
            include_alpn: true,
            fingerprint: &CHROME_DESKTOP,
            grease: None,
            mlkem_ek: None,
        }
    }

    #[test]
    fn generated_parses_via_the_parser() {
        let rnd = [0xAAu8; 32];
        let sid = [0xBBu8; 32];
        let ks = [0xCCu8; 32];
        let bytes = build_client_hello(&sample_inputs(&rnd, &sid, &ks)).unwrap();
        let parsed = parse_client_hello_record(&bytes).unwrap();
        assert_eq!(parsed.random, rnd);
        assert_eq!(parsed.session_id, sid);
        assert_eq!(parsed.x25519_key_share, ks);
    }

    #[test]
    fn grease_and_hybrid_keyshare_round_trip() {
        let rnd = [0x11u8; 32];
        let sid = [0x22u8; 32];
        let ks = [0x33u8; 32];
        let ek = [0x44u8; 1184];
        let grease = GreaseValues {
            cipher: 0x0A0A,
            group: 0x1A1A,
            ext_first: 0x2A2A,
            ext_last: 0x5A5A,
            version: 0x3A3A,
        };
        let bytes = build_client_hello(&ClientHelloInputs {
            random: &rnd,
            session_id: &sid,
            x25519_key_share: &ks,
            server_name: "example.com",
            include_alpn: true,
            fingerprint: &CHROME_DESKTOP,
            grease: Some(grease),
            mlkem_ek: Some(&ek),
        })
        .unwrap();
        // The bridge parser still extracts X25519 past the GREASE + hybrid
        // entries (it iterates key_share entries, skipping by length).
        let parsed = parse_client_hello_record(&bytes).unwrap();
        assert_eq!(parsed.x25519_key_share, ks);
        // GREASE cipher/group, the hybrid group, and the REAL ek all appear.
        let contains = |needle: &[u8]| bytes.windows(needle.len()).any(|w| w == needle);
        assert!(contains(&[0x0A, 0x0A]), "GREASE cipher present");
        assert!(contains(&[0x1A, 0x1A]), "GREASE group present");
        assert!(
            contains(&[0x11, 0xEC]),
            "hybrid X25519MLKEM768 group present"
        );
        assert!(contains(&ek), "real ML-KEM ek present in key_share");
        assert!(contains(&[0x3A, 0x3A]), "GREASE supported_versions present");
    }

    #[test]
    fn safari_template_omits_hybrid_keyshare() {
        // Safari does not advertise 0x11EC, so even with mlkem_ek=Some the
        // hybrid entry MUST NOT be emitted - advertised groups must equal sent
        // key_shares, or the inconsistency is itself a distinguisher.
        use crate::tls_fingerprint::SAFARI_DESKTOP;
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0x33u8; 32];
        let ek = [0x44u8; 1184];
        let bytes = build_client_hello(&ClientHelloInputs {
            random: &rnd,
            session_id: &sid,
            x25519_key_share: &ks,
            server_name: "example.com",
            include_alpn: true,
            fingerprint: &SAFARI_DESKTOP,
            grease: Some(GreaseValues::random()),
            mlkem_ek: Some(&ek),
        })
        .unwrap();
        assert!(
            !bytes.windows(2).any(|w| w == [0x11, 0xEC]),
            "Safari must not emit the hybrid group"
        );
        assert!(
            !bytes.windows(ek.len()).any(|w| w == ek),
            "Safari must not emit the ek"
        );
        let parsed = parse_client_hello_record(&bytes).unwrap();
        assert_eq!(parsed.x25519_key_share, ks);
    }

    /// Extract the extension-type sequence (in wire order) from a generated
    /// ClientHello record, skipping GREASE (0x?A?A). Used to assert the F4
    /// per-connection shuffle.
    fn extension_types(bytes: &[u8]) -> Vec<u16> {
        // record(5) + hs_header(4) + version(2) + random(32) + sid_len(1)+sid +
        // then cipher list, compression, extensions. Reuse the parser's shape by
        // walking from a known offset.
        let mut p = 5 + 4 + 2 + 32; // to session_id length
        let sid_len = bytes[p] as usize;
        p += 1 + sid_len;
        let cs_len = u16::from_be_bytes([bytes[p], bytes[p + 1]]) as usize;
        p += 2 + cs_len;
        let comp_len = bytes[p] as usize;
        p += 1 + comp_len;
        let ext_total = u16::from_be_bytes([bytes[p], bytes[p + 1]]) as usize;
        p += 2;
        let end = p + ext_total;
        let mut out = Vec::new();
        while p + 4 <= end {
            let t = u16::from_be_bytes([bytes[p], bytes[p + 1]]);
            let l = u16::from_be_bytes([bytes[p + 2], bytes[p + 3]]) as usize;
            if t & 0x0F0F != 0x0A0A {
                out.push(t);
            }
            p += 4 + l;
        }
        out
    }

    #[test]
    fn production_client_hello_has_structurally_valid_ech_grease() {
        // red-team HIGH #1: a production ClientHello MUST carry a GREASE ECH
        // (0xfe0d) whose framing is range-checkable, or a censor pins
        // "ML-KEM group but no ECH".
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0x33u8; 32];
        let ch = build_client_hello(&ClientHelloInputs {
            random: &rnd,
            session_id: &sid,
            x25519_key_share: &ks,
            server_name: "example.com",
            include_alpn: true,
            fingerprint: &CHROME_DESKTOP,
            grease: Some(GreaseValues::random()),
            mlkem_ek: None,
        })
        .unwrap();
        // Walk extensions to the ECH body.
        let mut p = 5 + 4 + 2 + 32;
        let sid_len = ch[p] as usize;
        p += 1 + sid_len;
        let cs_len = u16::from_be_bytes([ch[p], ch[p + 1]]) as usize;
        p += 2 + cs_len;
        let comp_len = ch[p] as usize;
        p += 1 + comp_len;
        let ext_total = u16::from_be_bytes([ch[p], ch[p + 1]]) as usize;
        p += 2;
        let end = p + ext_total;
        let mut ech: Option<&[u8]> = None;
        while p + 4 <= end {
            let t = u16::from_be_bytes([ch[p], ch[p + 1]]);
            let l = u16::from_be_bytes([ch[p + 2], ch[p + 3]]) as usize;
            if t == EXT_ENCRYPTED_CLIENT_HELLO {
                ech = Some(&ch[p + 4..p + 4 + l]);
            }
            p += 4 + l;
        }
        let body = ech.expect("production CH must carry a GREASE ECH extension");
        assert_eq!(body[0], 0x00, "ECHClientHelloType = outer");
        assert_eq!(&body[1..3], &[0x00, 0x01], "HKDF-SHA256");
        assert_eq!(&body[3..5], &[0x00, 0x01], "AES-128-GCM");
        let enc_len = u16::from_be_bytes([body[6], body[7]]) as usize;
        assert_eq!(enc_len, 32, "X25519 enc is 32 bytes");
        let payload_len = u16::from_be_bytes([body[8 + 32], body[8 + 32 + 1]]) as usize;
        assert_eq!(payload_len, ECH_GREASE_PAYLOAD_LEN);
        assert_eq!(body.len(), 1 + 4 + 1 + 2 + 32 + 2 + ECH_GREASE_PAYLOAD_LEN);
    }

    #[test]
    fn extension_order_shuffles_per_connection_but_set_is_stable() {
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0x33u8; 32];
        let mk = || {
            build_client_hello(&ClientHelloInputs {
                random: &rnd,
                session_id: &sid,
                x25519_key_share: &ks,
                server_name: "example.com",
                include_alpn: true,
                fingerprint: &CHROME_DESKTOP,
                grease: Some(GreaseValues::random()),
                mlkem_ek: None,
            })
            .unwrap()
        };
        // The canonical (non-GREASE) extension set, sorted - JA4-style.
        let mut canonical: Vec<u16> = CHROME_DESKTOP.extension_order.to_vec();
        canonical.sort_unstable();

        let mut saw_distinct_order = false;
        let first = extension_types(&mk());
        for _ in 0..24 {
            let types = extension_types(&mk());
            // Same SET every time (sorted equality) - JA4 stable.
            let mut sorted = types.clone();
            sorted.sort_unstable();
            assert_eq!(sorted, canonical, "extension set must be stable");
            if types != first {
                saw_distinct_order = true;
            }
            // Every generated CH must still parse.
            assert!(parse_client_hello_record(&mk()).is_ok());
        }
        assert!(
            saw_distinct_order,
            "F4: extension order must vary across connections"
        );
    }

    #[test]
    fn deterministic_when_no_grease() {
        // grease=None (tests) -> canonical order, byte-identical across calls.
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0x33u8; 32];
        let mk = || build_client_hello(&sample_inputs(&rnd, &sid, &ks)).unwrap();
        assert_eq!(mk(), mk(), "no-GREASE build must be deterministic");
        // And the emitted order equals the template's canonical order, minus the
        // production-only GREASE ECH (random payload, omitted in the no-GREASE
        // deterministic path so the build stays byte-reproducible).
        let expected: Vec<u16> = CHROME_DESKTOP
            .extension_order
            .iter()
            .copied()
            .filter(|&e| e != EXT_ENCRYPTED_CLIENT_HELLO)
            .collect();
        assert_eq!(extension_types(&mk()), expected);
    }

    #[test]
    fn output_starts_with_valid_tls_record_header() {
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let bytes = build_client_hello(&sample_inputs(&rnd, &sid, &ks)).unwrap();
        assert_eq!(bytes[0], 0x16); // handshake
        assert_eq!(&bytes[1..3], &[0x03, 0x01]); // legacy version
                                                 // Record length matches body
        let rec_len = u16::from_be_bytes([bytes[3], bytes[4]]) as usize;
        assert_eq!(rec_len + 5, bytes.len());
        // Handshake type
        assert_eq!(bytes[5], 0x01);
    }

    #[test]
    fn works_without_alpn() {
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let bytes = build_client_hello(&ClientHelloInputs {
            include_alpn: false,
            ..sample_inputs(&rnd, &sid, &ks)
        })
        .unwrap();
        let parsed = parse_client_hello_record(&bytes).unwrap();
        assert_eq!(parsed.session_id, sid);
    }

    #[test]
    fn rejects_empty_sni() {
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let mut inputs = sample_inputs(&rnd, &sid, &ks);
        inputs.server_name = "";
        assert!(build_client_hello(&inputs).is_err());
    }

    #[test]
    fn rejects_non_ascii_sni() {
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let mut inputs = sample_inputs(&rnd, &sid, &ks);
        // IDN is out of scope for MVP; must be ASCII already.
        inputs.server_name = "exämple.com";
        assert!(build_client_hello(&inputs).is_err());
    }

    #[test]
    fn rejects_oversized_sni() {
        let long = "a".repeat(254);
        let rnd = [0u8; 32];
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let mut inputs = sample_inputs(&rnd, &sid, &ks);
        inputs.server_name = &long;
        assert!(build_client_hello(&inputs).is_err());
    }

    #[test]
    fn different_randoms_produce_different_bytes() {
        let sid = [0u8; 32];
        let ks = [0u8; 32];
        let r1 = [0x11u8; 32];
        let r2 = [0x22u8; 32];
        let b1 = build_client_hello(&sample_inputs(&r1, &sid, &ks)).unwrap();
        let b2 = build_client_hello(&sample_inputs(&r2, &sid, &ks)).unwrap();
        assert_ne!(b1, b2);
    }

    #[test]
    fn fuzz_parse_all_generated() {
        // Every shape we can emit MUST round-trip.
        use proptest::prelude::*;
        proptest!(ProptestConfig::with_cases(128), |(
            rnd in prop::array::uniform32(any::<u8>()),
            sid in prop::array::uniform32(any::<u8>()),
            ks in prop::array::uniform32(any::<u8>()),
            sni in "[a-z0-9][a-z0-9\\-]{0,60}\\.[a-z]{2,10}",
            alpn in any::<bool>(),
            ek_fill in any::<u8>(),
            use_grease in any::<bool>(),
            use_hybrid in any::<bool>(),
        )| {
            // Also fuzz the GREASE + hybrid-key_share layout so the load-bearing
            // client_shares_len math round-trips across every combination.
            let ek_buf = [ek_fill; 1184];
            let bytes = build_client_hello(&ClientHelloInputs {
                random: &rnd,
                session_id: &sid,
                x25519_key_share: &ks,
                server_name: &sni,
                include_alpn: alpn,
                fingerprint: &CHROME_DESKTOP,
                grease: if use_grease { Some(GreaseValues::random()) } else { None },
                mlkem_ek: if use_hybrid { Some(&ek_buf) } else { None },
            }).unwrap();
            let parsed = parse_client_hello_record(&bytes).unwrap();
            prop_assert_eq!(parsed.random, rnd);
            prop_assert_eq!(parsed.session_id, sid);
            prop_assert_eq!(parsed.x25519_key_share, ks);
        });
    }
}
